plugins {
    id 'com.gtnewhorizons.gtnhgradle'
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

version = "${projecte_version}"
group= "java.moze_intel" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "ProjectEX"

minecraft {
    mcVersion = "${minecraft_version}"
    extraTweakClasses = ["org.spongepowered.asm.launch.MixinTweaker"]
    // runDir = "run"

    // replace "@VERSION@", project.version
    // replaceIn "PECore.java"
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

repositories {
    maven {
        // RetroFuturaGradle
        name "GTNH Maven"
        url "https://nexus.gtnewhorizons.com/repository/public/"
    }
    maven {
        name "JitPack"
        url "https://jitpack.io"
    }
    gradlePluginPortal()
    mavenCentral()
    mavenLocal()
}
 
dependencies {
    testImplementation group: 'junit', name: 'junit', version:'4.12'

    implementation "com.github.GTNewHorizons:Chisel:2.17.8-GTNH-pre"
    implementation "com.github.GTNewHorizons:GTNHLib:0.8.0:dev"
    implementation "com.github.GTNewHorizons:CodeChickenCore:1.4.10"
    implementation "com.github.GTNewHorizons:CodeChickenLib:1.3.0"
    implementation "com.github.GTNewHorizons:NotEnoughItems:2.8.40-GTNH"

    implementation "com.github.GTNewHorizons:CraftTweaker:3.4.2"
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", minecraft_version

    filesMatching('mcmod.info') {
        expand 'version':project.version, 'mcversion':minecraft_version
    }
}

// Dev jar (deobfuscated)
task devJar(type: Jar) {
    from sourceSets.main.output
    archiveClassifier = 'dev'
    archiveVersion = "${project.version}"
}

artifacts {
    archives devJar
}

idea.module.inheritOutputDirs = true

tasks.named('reobfJar') { dependsOn devJar }

tasks.named('runClient') {
    dependsOn devJar
}
